### ISSUE TITLE
Filebeat kafka output doesn't work

### ISSUE THREAD

**Issue by xkrt** [Azure/azure-event-hubs-for-kafka#37]
Description
===========
I'm trying to use [Filebeat](https://www.elastic.co/products/beats/filebeat) 6.6.0 with Event Hubs as kafka output and it doesn't work.

How to reproduce
================
Filbeat config, that takes input from stdin and writes to Kafka Event Hub.
Also I create reproduction with Vagrant: https://github.com/xkrt/azure-events-hub-filebeat-issue.

```/etc/filebeat/filebeat.yml```:
```
filebeat.inputs:
  - type: stdin

output.kafka:
  topic: thehub
  required_acks: 1
  client_id: filebeat
  version: '1.0.0'
  hosts:
    - "thenamespace.servicebus.windows.net:9093"

  username: "$ConnectionString"
  password: "Endpoint=sb://thenamespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=MYKEY"
  ssl.enabled: true

logging:
  level: debug
  to_files: false
  to_syslog: false
```
Then start filebeat:
```
/usr/share/filebeat/bin/filebeat -c /etc/filebeat/filebeat.yml -e
```

And write anything to stdin with Enter for EOL:
```
hello\n
```

And you get a lot of DEBUG error messages like:
```
INFO    kafka/log.go:53 kafka message: Successful SASL handshake
INFO    kafka/log.go:53 SASL authentication successful with broker his-logs-stg.servicebus.windows.net:9093:4 - [0 0 0 0]
INFO    kafka/log.go:53 Connected to broker at thenamespace.servicebus.windows.net:9093 (registered as #0)

DEBUG   [kafka] kafka/client.go:251     finished kafka batch
DEBUG   [kafka] kafka/client.go:265     Kafka publish failed with: kafka server: The requested operation is not supported by the message format version.
```

Which means actually [UNSUPPORTED_FOR_MESSAGE_FORMAT](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol) (see https://github.com/Shopify/sarama/blob/master/errors.go#L130).

I tried various `version` value in config with no luck.

For all kafka output plugin options see [docs](https://www.elastic.co/guide/en/beats/filebeat/master/kafka-output.html) and [reference config](https://github.com/elastic/beats/blob/master/filebeat/filebeat.reference.yml#L1267).

Checklist
=========
Please provide the following information:
 
 - [x] Verified that port 9093 is not blocked by firewall
 - [x] Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported)
 - [x] Sample you're having trouble with: `filbeat config`
 - [x] Apache Kafka version: `1.0.0 and above`
 - [x] Kafka client configuration: `whole config above`
 - [x] Namespace and EventHub/topic name
 - [x] Consumer or producer failure `producer failure`
 - [x] Timestamp in UTC `2019-02-14T13:26:47.212Z`
 - [x] Client ID `filebeat`
 - [x] Provide all logs (with debugging enabled if possible) or exception call stack
 - [x] Standalone repro `https://github.com/xkrt/azure-events-hub-filebeat-issue`
 - [x] Operating system: `CentOS 7.6 or Ubuntu 16.04`
 - [x] Critical issue
